### ISSUE TITLE
Commands Are Being Run Twice

### ISSUE THREAD

**Issue by FireController1847** [ELCHILEN0/AutoMessage#39]
Here is my config:
```yml
settings:
  enabled: true
  min-players: 0
  log-to-console: true
message-lists:
  regular:
    enabled: true
    interval: 1
    expiry: -1
    random: false
    messages:
    - /say 1
    - /say 2
```
Using this config, every second "/say 1" is being run twice, and "/say 2" is being run twice.
